--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/metal888/Downloads/wallpaper_d/New/cozyhome.jpg"

-- Special
background="#1e180c"
foreground="#c6c5c2"
cursor="#c6c5c2"

-- Colors
color0="#1e180c"
color1="#715543"
color2="#9A5831"
color3="#B3562A"
color4="#9D6B47"
color5="#DEA862"
color6="#DBAD67"
color7="#c6c5c2"
color8="#70695c"
color9="#715543"
color10="#9A5831"
color11="#B3562A"
color12="#9D6B47"
color13="#DEA862"
color14="#DBAD67"
color15="#c6c5c2"
