# Shell variables
# Generated by 'wal'
wallpaper="/home/metal888/Downloads/wallpaper_d/New/cozyhome.jpg"

# Special
background='#1e180c'
foreground='#c6c5c2'
cursor='#c6c5c2'

# Colors
color0='#1e180c'
color1='#715543'
color2='#9A5831'
color3='#B3562A'
color4='#9D6B47'
color5='#DEA862'
color6='#DBAD67'
color7='#c6c5c2'
color8='#70695c'
color9='#715543'
color10='#9A5831'
color11='#B3562A'
color12='#9D6B47'
color13='#DEA862'
color14='#DBAD67'
color15='#c6c5c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
