--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/metal888/Downloads/wallpaper_d/planet_meteors.jpeg"

-- Special
background="#0F0C0B"
foreground="#c9c8c8"
cursor="#c9c8c8"

-- Colors
color0="#0F0C0B"
color1="#525B61"
color2="#A85524"
color3="#C3945A"
color4="#54748A"
color5="#9369AC"
color6="#6891AA"
color7="#c9c8c8"
color8="#8c8c8c"
color9="#525B61"
color10="#A85524"
color11="#C3945A"
color12="#54748A"
color13="#9369AC"
color14="#6891AA"
color15="#c9c8c8"
