[colors]
background = '#1e180c8e'
black = '#1e180c'
blue = '#715543'
cursor = '#c6c5c2'
cyan = '#9A5831'
foreground = '#c6c5c2'
green = '#B3562A'
magenta = '#9D6B47'
red = '#DEA862'
tabs = '#c6c5c2'
tabs-active = '#DBAD67'
white = '#c6c5c2'
yellow = '#c6c5c2'
dim-black = '#1e180c8e'
dim-blue = '#7155438e'
dim-cyan = '#9A58318e'
dim-foreground = '#c6c5c28e'
dim-green = '#B3562A8e'
dim-magenta = '#9D6B478e'
dim-red = '#DEA8628e'
dim-white = '#DBAD678e'
dim-yellow = '#c6c5c28e'
light-black = '#715543'
light-blue = '#9A5831'
light-cyan = '#B3562A'
light-foreground = '#9D6B47'
light-green = '#DEA862'
light-magenta = '#DBAD67'
light-red = '#c6c5c2'
light-white = '#715543'
light-yellow = '#9A5831'
