# pywal theme for ghostty

background = 1e180c
foreground = c6c5c2
cursor-color = c6c5c2
selection-background = c6c5c2
selection-foreground = 1e180c

palette = 0=#1e180c
palette = 1=#715543
palette = 2=#9A5831
palette = 3=#B3562A
palette = 4=#9D6B47
palette = 5=#DEA862
palette = 6=#DBAD67
palette = 7=#c6c5c2
palette = 8=#70695c
palette = 9=#715543
palette = 10=#9A5831
palette = 11=#B3562A
palette = 12=#9D6B47
palette = 13=#DEA862
palette = 14=#DBAD67
palette = 15=#c6c5c2
