--autogenerated = 1

--monitor = eDP-1,1366x768@60,0x0,1
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

local mainMod = "SUPER"
local terminal = "alacritty"
local filemanager = "dolphin"
local browser = "brave"
local pdfreader = "okular"
local ebookreader = "foliate"

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER+SHIFT + T", hl.dsp.exec_cmd("foot"))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(filemanager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("DISPLAY=:0 " .. browser .. " --ozone-platform=x11"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(pdfreader))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("DISPLAY=:0 GDK_BACKEND=x11 " .. ebookreader))
hl.bind("ALT + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("ALT+SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))
-- TODO: manual review on line 21 — no mapping for dispatcher "workspaceopt"
-- hl.bind(mainMod .. " + I", hl.dsp.workspaceopt("allfloat"))
hl.bind("SUPER+SHIFT + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + F4", hl.dsp.window.close())
hl.bind("F12", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + N", hl.dsp.focus({ workspace = "empty" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))


-- hl.bind("SUPER+SHIFT + right", hl.dsp.exec_cmd("resizeactive 40 0"))
-- hl.bind("SUPER+SHIFT + left", hl.dsp.exec_cmd("resizeactive -40 0"))
-- hl.bind("SUPER+SHIFT + up", hl.dsp.exec_cmd("resizeactive 0 -40"))
-- hl.bind("SUPER+SHIFT + down", hl.dsp.exec_cmd("resizeactive 0 40"))


-- PrtSc: Capture whole screen
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m output -m eDP-1 -o ~/Pictures"))
-- Super + Shift + PrtSc: HD capture of whole screen
hl.bind("SUPER + SHIFT + Print", hl.dsp.exec_cmd("bash -c 'grim -l 0 -t png - | tee ~/Pictures/$(date +%Y%m%d_%Hh%Mm%Ss)_grim_full.png | wl-copy'"))
-- Super + PrtSc: Capture specific window
hl.bind("SUPER + Print", hl.dsp.exec_cmd("hyprshot -m window -o ~/Pictures"))
-- Ctrl + Shift + PrtSc: HD capture of selected region
hl.bind("CTRL + SHIFT + Print", hl.dsp.exec_cmd("bash -c 'sel=$(slurp -b 00000000 -c 00000000 -s 00000000) && grim -l 0 -t png -g \"$sel\" - | tee ~/Pictures/$(date +%Y%m%d_%Hh%Mm%Ss)_grim_cut.png | wl-copy'"))
-- Shift + PrtSc: Lowres capture of selected region
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grimblast -f copysave area"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 960+"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 960-"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("amixer set Master 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("amixer set Master 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("amixer set Master toggle"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("ALT + X", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("ALT + Z", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("ALT + C", hl.dsp.exec_cmd("playerctl next"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("swaylock"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("emote"))

-- rofi animation
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "slide",
})
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("wlsunset -T 5000"))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("pkill wlsunset"))
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("wlogout"))

-- Move Windows with mainMod + arrow keys
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())
hl.bind("SUPER + Control_L", hl.dsp.window.drag())
hl.bind("SUPER + ALT_L", hl.dsp.window.resize())

-- Resize Floating window
hl.bind("SUPER + ALT + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind("SUPER + ALT + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind("SUPER + ALT + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind("SUPER + ALT + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- TODO: manual review — malformed env on line 93: HYPRLAND_NO_SD_NOTIFY=1
-- TODO: manual review — malformed env on line 94: HYPRLAND_NO_SD_VARS=1

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_TERMINAL", "tilix")
--env = XDG_MENU_PREFIX,plasma- run kbuildsycoca6

--env = XDG_MENU_PREFIX,arch- kbuildsycoca6
--env = QT_QPA_PLATFORM,wayland
--env = QT_QPA_PLATFORMTHEME,qt6ct
--env = QT_QPA_PLATFORMTHEME,gtk4

hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
--env = QT_STYLE_OVERRIDE,qt6ct
hl.env("QT_QUICK_CONTROLS_STYLE", "org.kde.desktop")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")

--env = QT_SCALE_FACTOR,1
--env = QT_STYLE_OVERRIDE,kvantum
--env = QT_STYLE_OVERRIDE,qt6ct

hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("SDL_VIDEORIVER", "wayland")
hl.env("GDK_SCALE", "1")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("TERMINAL", "tilix")
hl.env("VISUAL", "nvim")
hl.env("EDITOR", "nvim")
hl.env("BROWSER", "brave")
hl.env("GTK_THEME", "Adwaita-dark")
-- material_cursors goes in ~/.local/share/icons/
-- it's included in dirtydots config
hl.env("XCURSOR_THEME", "material_cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "material_cursors")
hl.env("HYPRCURSOR_SIZE", "24")

--env = GTK_IM_MODULE,ibus
--env = QT_IM_MODULE,ibus
--XMODIFIERS=@im=ibus

-- exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

-- exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME

--exec-once = easyeffects --gapplication-service &
--exec-once = flatpak run com.github.wwmm.easyeffects > /dev/null 2>&1 &

--exec-once = ibus-daemon -drx
--exec-once = fcitx5 &
--exec-once = eww daemon

hl.curve("overshot", { type = "bezier", points = { { 0, 0.61 }, { 0.22, 1.12 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3.8,
    bezier = "default",
    style = "popin 50%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 4,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 4,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3.8,
    bezier = "overshot",
    style = "slidevert",
})

hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "allow" })


-- Toggle the music scratchpad
hl.bind("SUPER + Q", hl.dsp.workspace.toggle_special("music"))
-- Auto-launch cmus the first time the workspace is created (empty)
hl.workspace_rule({
    workspace = "special:music",
    on_created_empty = "alacritty -e cmus",
})

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  overview { ... }
]]

hl.config({
    general = {
        --gaps_in = 2
        gaps_in = 2,
        --gaps_out = 5
        gaps_out = 5,
        --border_size = 2
        border_size = 2,
        resize_on_border = true,
        --col.active_border = rgba(00005577)
        --col.active_border = rgba(3584e450)
        --col.active_border = rgba(ff000060)
        --blue
        --col.active_border = rgba(3584e4aa) #rgba(53, 132, 228, 0.4)
        -- LAST ONE IS CURRENT
        col = {
            active_border = { colors = { "rgba(a3582dff)", "rgba(a3582dff)" }, angle = 45 }, -- same shade as the previous one but a bit darker
        },
        layout = "dwindle",
        --goldenhour
        --col.active_border = rgba(daa520cc) rgba(daa520cc) 45deg
        --col.inactive_border = rgba(daa520cc) rgba(daa520cc) 45deg
    },
    decoration = {
        rounding = 13,
        active_opacity = 1,
        --inactive_opacity = 0.45
        --active_opacity = 0.75
        --inactive_opacity = 0.45
        --fullscreen_opacity = 0
        --drop_shadow = true
        -->>>shadow_range = 5
        -->>>shadow_render_power = 5
        --col.shadow = rgb(daa520)
        -->>>col.shadow = rgb(3584e4)
        shadow = {
            enabled = false,
            range = 1,
            render_power = 1,
            color = "rgb(3584e4)",
        },
        blur = {
            -- enabled = true
            enabled = true,
            --size = 4
            --passes = 4
            size = 4,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            --contrast = 2.0
            popups = true,
            --blurls=waybar
            -- blurls=wlogout
        },
        glow = {
            enabled = false,
            range = 5,
            color = 0xa3582dff,
        },
        wobble = {
            -- enabled = true
        },
    },
    input = {
        touchpad = {
            natural_scroll = true,
            disable_while_typing = false,
        },
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        repeat_rate = 35,
        repeat_delay = 400,
        follow_mouse = 2,
        accel_profile = "flat",
        --sensitivity = 0.5
        sensitivity = 0.7,
        float_switch_override_focus = 1,
    },
    cursor = {
        hide_on_key_press = true,
        no_hardware_cursors = true,
        inactive_timeout = 2,
        --no_warps = true
        --min_refresh_rate = 30
        --enable_hyprcursor = false
    },
    gestures = {
        -- workspace_swipe = true
    },
    animations = {
        enabled = 1,
        -- bezier=overshot,0.05,0.9,0.1,1.1 # Version 1
        -- bezier=overshot,0.13,0.99,0.29,1.09 # Version 2
        -- Add this line to make fullscreen windows slide from the top
        -- animation=fullscreen,1,3.8,overshot,slidetop
    },
    misc = {
        disable_hyprland_logo = true,
        -- vfr = true
        enable_swallow = true,
        focus_on_activate = true,
        disable_autoreload = true,
    },
    binds = {
        allow_workspace_cycles = true,
    },
    dwindle = {
        permanent_direction_override = true,
        preserve_split = true,
    },
    -- bind = SUPER, Tab, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
    -- Toggle the music scratchpad
    -- Auto-launch cmus the first time the workspace is created (empty)
    -- PLUGINS
    -- plugin: https://github.com/KZDKM/Hyprspace
    -- bind = SUPER, TAB, overview:toggle
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("awww-daemon -f xrgb &")
    hl.exec_cmd("awww img ~/Wallpapers/brownroom1.png")
    hl.exec_cmd("waybar -c $HOME/.config/waybar/config.jsonc -s $HOME/.config/waybar/style.css &")
    hl.exec_cmd("flatpak run com.github.wwmm.easyeffects --gapplication-service &")
    hl.exec_cmd("swaync")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("hyprpm reload")
end)
